# fly.toml app configuration file generated for lambdacrate-admin-client on 2024-11-30T18:11:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lambdacrate-admin-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
