/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/y4oMklDLj9J
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"


export function LandingPage() {
  return (
    <div className="bg-[#121212] min-h-screen text-white">
      <header className="flex justify-between items-center p-6 border-b border-gray-700">
        <h1 className="text-3xl font-bold">lambdacrate-example</h1>
        <div className="flex space-x-4">
          <Button className="border-gray-600 text-white" variant="outline">
            Project Status
          </Button>
          <Button>Connect</Button>
        </div>
      </header>
      <main className="px-6 py-4">
        <section className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Welcome to your new project</h2>
          <p className="text-gray-400">
            Your project has been deployed on its own instance, with its own API and dashboard all set up and ready to use.
          </p>
        </section>
        <section className="mb-6">
          <h3 className="text-lg font-semibold mb-2">Get started by building out your database</h3>
          <p className="text-gray-400 mb-4">
            Start building your app by creating tables and inserting data. Our Table Editor makes Postgres as easy to
            use as a spreadsheet, but there&apos;s also our SQL Editor if you need something more.
          </p>
          <div className="flex space-x-2">
            <Button variant="secondary">Table Editor</Button>
            <Button variant="secondary">SQL Editor</Button>
            <Button variant="secondary">About Database</Button>
          </div>
        </section>
      
   
      </main>
    </div>
  )
}
