# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: "echo API_URL $API_URL"
     
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
          GITHUB_URL: ${{ secrets.GHUB_URL }}
          GITHUB_CLIENT_ID: ${{ secrets.GHUB_CLIENT_ID }}
          GITHUBCLIENT_SECRET: ${{ secrets.GHUB_CLIENT_SECRET }}
          PUBLIC_BASE_URL: ${{ secrets.PUBLIC_BASE_URL }}
          PUBLIC_STRIPE_KEY: ${{ secrets.PUBLIC_STRIPE_KEY }}
